name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  font_awesome_flutter: ^10.9.0
  http: ^1.5.0
  google_fonts: ^6.3.0
  location: ^8.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.5.3
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

flutter_intl:
  enabled: true
